### ISSUE TITLE
Playlist <table> does not get updated after new song is added to track list

### ISSUE THREAD

**Issue by amir734jj** [vmudigal/ngx-audio-player#50]
I am using the "Advanced Player" and when I push a new track to the `msaapPlaylist`, the playlist `<table>` does not get updated. I think this is a bug.

Also, is there a way to get the index of the current song being currently played? maybe it would be great if you could expose `AudioPlayerService`

**Comment by dtyaden** [comment]
Had this problem today as well... in case you're still on this or anyone else comes across this issue where the advanced player doesn't update when you modify the playlist at all:

You need to directly update the player's `playlist` and call `ngOnInit`.

```
var player: MatAdvancedAudioPlayerComponent = getAdvancedAudioPlayer(); //get the advanced audio player somehow
    player.playlist = this.tracks //tracks is just a Track array.
    player.ngOnInit(); //re call the ngOnInit method which re setup the audio player service.
```

If you look at the advanced audio player, there's a set method on playlist

```
@Input()
    set playlist(playlist: Track[]) {
        this.playlistData = playlist;
        this.ngOnInit();
    }
```

but for some reason it doesn't get called... is it because it's an input? probably a bug idk but i think setting playlist and manually calling ngOnInit will work in a pinch

**Comment by vmudigal** [comment]
Fixed in https://www.npmjs.com/package/ngx-audio-player/v/9.1.0
