### ISSUE TITLE
Not able to play on mobile (IOS)

### ISSUE THREAD

**Issue by dcstang** [vmudigal/ngx-audio-player#53]
Hi and thanks for this cool npm. Love it, and works brilliant on chrome desktop.
But it doesn't play on mobile chrome browers on my phone or tablet. The play button does not appear at all, though the rest of the UI is there.

**Comment by ewwwgiddings** [comment]
This is also an issue for me.

The advanced player has the play button showing. I used advanced player with all options false including title thinking it would work. That doesn't work either.

Nothing plays on mobile.

This is how I initialize it with an mp3:
`  <mat-advanced-audio-player 
  [playlist]="msaapPlaylist" 
  [displayTitle]="false" 
  [displayPlaylist]="false"
  [expanded]="false" 
  [displayVolumeControls]="true">
  </mat-advanced-audio-player>`

**Comment by ewwwgiddings** [comment]
One thing that may provide a clue is that the audio does play on mobile if you tap the track in the advanced player. The play button does not show up, but it does if you tap a song to start the song.

This says to me that the error on mobile is with the initializing of the player's audio. The audio plays on mobile, but the player has an error with initializing it.

My guess, because I saw various setTimeout in the code, is that perhaps it's an order of operations (Angular lifecycle change) or a setTimeout needed.

**Comment by ewwwgiddings** [comment]
Maybe it's related to the need for user interaction before playing media?

**Comment by vmudigal** [comment]
Could you help me replicate the issue? 

Know issue: does not play if the audio url is broken.

The working sample is at https://ngx-audio-player-v9-advanced.stackblitz.io

**Comment by ewwwgiddings** [comment]
Hi, Yes you can duplicate it by using an iPhone and going to your link here:
https://vmudigal.github.io/ngx-audio-player/

**Comment by vmudigal** [comment]
Fixed the issue in https://github.com/vmudigal/ngx-audio-player/commit/93ef04e9e0cf722256357269b4a08303b47fe025.

Fixed available in https://www.npmjs.com/package/ngx-audio-player/v/9.0.7
