### ISSUE TITLE
Audio won't load/play on iOS

### ISSUE THREAD

**Issue by dmbrenneman** [vmudigal/ngx-audio-player#7]
On iOS, the loading spinner just spins continuously and the audio can never be played. It works fine on Windows in multiple browsers, but on iOS it never loads using either Safari or Chrome browser.

**Comment by Big18Al** [comment]
I'm having the same issue on windows

**Comment by vmudigal** [comment]
I have noticed this issue when the URL of the audio is broken. Could you please confirm if thats the scenario here?

**Comment by Big18Al** [comment]
Yes, I got it working. The url was the issue

**Comment by cedricsandars** [comment]
@vmudigal - This issue is happening in all iPhones. Both simulator as well as real devices. I also doubted that it could be due to a broken URL, but even in the working demo provided in the documentation, the basic player keeps on loading.

![Skype_Picture_2020_01_13T08_00_07_322Z](https://user-images.githubusercontent.com/2046221/72240048-e6521a00-3608-11ea-962e-12680e0a2f63.jpeg)

**Comment by ewwwgiddings** [comment]
Now the play button doesn't show on the example when using an iPhone. Has anyone solved this? I am using it on my site but if it doesn't work on iPhone I need to find an alternative.

**Comment by ewwwgiddings** [comment]
@vmudigal It's only the basic audio player. The advanced one is fine. Maybe the problem is in the difference between the two.
